CREATE TABLE IF NOT EXISTS deck
(
    id VARCHAR(36) NOT NULL,
    name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT deck_pk PRIMARY KEY (id)
)